 - name: cleanup repos/rules and other stuff on seconion distributed master node
  hosts: managernode
  become: true
  become_method: sudo
  vars_files: vars/secrets.yml

  tasks:

        - name: Copy suricata rules to security onion manager
          copy:
            src: /home/ansible/ansible/secOnion-custom/files/emerging-all.rules
            dest: /nsm/repo/rules/emerging-all.rules
            owner: {{owner}}
            group: {{group}}
            mode: 0644

        - name: Copy suricata rules md5 file to security onion manager
          copy:
            src: /home/ansible/ansible/secOnion-custom/files/emerging-all.rules.md5
            dest: /nsm/repo/rules/emerging-all.rules.md5
            owner: {{owner}}
            group: {{group}}
            mode: 0644

        - name: Run rule update
          shell: "so-rule-update"

        - name: Set zeek processor numbers in salt configuration
          lineinfile:
            dest: /opt/so/saltstack/local/pillar/minions/seconion-sensornode_sensor.sls
            regexp: '^  zeek_lbprocs.*'
            line: '  zeek_lbprocs: {{zeek_lbprocs}}'
            backrefs: yes

        - name: Set suricata processor numbers in salt configuration
          lineinfile:
            dest: /opt/so/saltstack/local/pillar/minions/seconion-sensornode_sensor.sls
            regexp: '^  suriprocs.*'
            line: '  suriprocs: {{suriprocs}}'
            backrefs: yes

        - name: replace esheap line in seconion manager minion file
          replace:
            path: /opt/so/saltstack/local/pillar/minions/seconion-managernode_manager.sls
            regexp: '^  esheap.*'
            replace: '  esheap: {{esheap}}'

        - name: Set searchnode elasticsearch heap space in salt configuration
          lineinfile:
            dest: /opt/so/saltstack/local/pillar/minions/seconion-searchnode_searchnode.sls
            regexp: '^  esheap.*'
            line: '  esheap: {{esheap}}'
            backrefs: yes

        - name: rerun salt update
          shell: "salt -t 240 \\* state.highstate"
          ignore_errors: yes
