- name: configure seconion distributed search node
  hosts: searchnode
  become: true
  become_method: sudo
  vars_files: vars/secrets.yml

  tasks:
        - name: Unconditionally reboot searchnode
          reboot:

        - name: Copy SecOnion searchnode setup configuration file
          copy:
            src: /home/ansible/ansible/secOnion-custom/files/distributed-airgap-search
            dest: /home/{{so_user}}/SecurityOnion/setup/automation/distributed-airgap-search
            owner: {{owner}}
            group: {{group}}
            mode: 0644

        - name: Add Static IP configuration to ifc-ens192
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "IPADDR={{search_ip}}"
        - name: Add Prefix
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "PREFIX={{search_ip_prefix}}"
        - name: Add Gateway
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "GATEWAY={{search_gateway}}"
        - name: Add DNS
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            insertbefore: "^IPV4_FAILURE_FATAL=no"
            line:  "DNS1={{search_dns}}"
        - name: Set Boot Protocol to static
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            regexp: '^BOOTPROTO=dhcp'
            line: 'BOOTPROTO=static'
            backrefs: yes
        - name: Delete IPV6 lines
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6INIT=yes'
            backrefs: yes
        - name: Delete IPV6 line2
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_AUTOCONF=yes'
            backrefs: yes
        - name: Delete IPV6 line3
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_DEFROUTE=yes'
            backrefs: yes
        - name: Delete IPV6 line 4
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_FAILURE_FATAL=no'
            backrefs: yes
        - name: Delete IPV6 Line 5
          lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-ens192
            state: absent
            regexp: '^IPV6_ADDR_GEN_MODE=stable-privacy'
            backrefs: yes

        - name: Unconditionally reboot the machine with all defaults
          reboot:
